### ISSUE TITLE
Does not shows the real image

### ISSUE THREAD

**Issue by Shibu-N** [shalkam/react-cornerstone-example#1]
I'm trying to use your example for viewing the DICOM image. But when I'm trying to render the DICOM Image it does not shows the real image or it could be said as the image gets pixelated or corrupted. I'm using the ant design upload component to convert the image to base64. Is there any other way to resolve the problem? Or is it an conversion error in the upload component that I've been using. 

![image](https://user-images.githubusercontent.com/32569397/41832201-aded6214-7868-11e8-802d-d5d38f268f6e.png)

Thanks in advance...

**Comment by shalkam** [comment]
Hi,
So, it's definitely capable of showing real DICOM images, I've already done that on another project.
I will take a look at it and share my code here or update the repository.

**Comment by shalkam** [comment]
today probably

**Comment by shalkam** [comment]
Hey, 
I've just updated the repository to use a real DICOM image and it's using this library https://github.com/rii-mango/Daikon for parsing.
